# Generated by Django 4.1.5 on 2023-01-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(help_text='Product brand name', max_length=100)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(help_text='category name', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, help_text='created time of category')),
                ('updated_at', models.DateField(auto_now=True, help_text='category name updated time')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='name of product', max_length=100)),
                ('product_description', models.TextField(blank=True)),
                ('product_quantity', models.IntegerField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_availability', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Product created time')),
                ('updated_at', models.DateField(auto_now=True, help_text='Product updated time')),
                ('brand', models.ForeignKey(help_text='Product Brand', on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(help_text='Product Category', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
